Consistency Cleanup
ethereum-optimism/contracts pull request #127
Opened 2020-12-11 17:52 UTC by axchu

### Fixes
- Fixes https://github.com/ethereum-optimism/roadmap/issues/281

## Contributing Agreement

- [ ] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

2020-12-11 17:55 UTC, axchu commented
The style we have decided to follow:
- for the Library contracts, `internal` functions will not have underscores, `private` functions will.  There are no public functions.
- for the OVM contracts, `public` functions will not have underscores, `internal` and `private` functions will.

2020-12-11 20:25 UTC, kfichter requested changes
Looks good, requested a few minor changes.

2020-12-11 20:25 UTC, kfichter commented on contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
> +    function _deployTransitioner(bytes32 _preStateRoot, bytes32 _txHash) private {
Would you mind just changing the structure of this signature to match the other signatures in this file (with each parameter on its own line, and `private` on its own line too) + add a function comment here? Thank you!

2020-12-11 20:25 UTC, kfichter commented on contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
> +    function _cancelStateTransition(
Same as above with fixing signature + adding a function comment.

2020-12-11 22:28 UTC, kfichter commented on contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol
> +    // NB: Stack too deep :/
We can get rid of the "stack too deep" comments here

2020-12-12 18:45 UTC, kfichter approved these changes
LGTM! Approving but let's wait to merge until we're sure that we want to make updates to master.

2020-12-16 18:33 UTC, ben-chain commented
This does not change any public interfaces, should be good to merge.

2021-03-09 17:57 UTC, closed without merging