fix: licenses and constructor modifiers
ethereum-optimism/contracts pull request #265
Opened 2021-03-02 12:32 UTC by vaibhavchellani

## Description
Addresses compiler warnings.
### Fixes
- Fixes #255 

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

2021-03-02 12:37 UTC, vaibhavchellani commented
Created a draft PR to check with @maurelian if we are on the same page. 

Let me know if it's all good and I will send more commits to remove other warnings.

2021-03-02 20:25 UTC, maurelian requested changes
Looking good to me, thank you very much for taking this on! 🙏

2021-03-02 20:25 UTC, maurelian commented on contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol
> +    )  {
Let's also mark this contract as `abstract`.

2021-03-02 20:25 UTC, maurelian commented on contracts/optimistic-ethereum/libraries/utils/Lib_ReentrancyGuard.sol
> +    constructor () {
Please also mark this contract as `abstract`.

2021-03-04 07:26 UTC, vaibhavchellani commented
@maurelian here are some questions where some help is appreciated:

- what should we rename [push2](https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol#L121) to?
- how to remove `Unused function parameter` warnings in the mock contracts, or should we let it be? 
- should we also attempt to remove warnings originating from `UniswapV2ERC20`

2021-03-04 15:41 UTC, maurelian commented
> * what should we rename [push2](https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol#L121) to?

Let's try `pushTwo`, and we'll see what the other maintainers think when the full PR is ready for review.

> * how to remove `Unused function parameter` warnings in the mock contracts, or should we let it be?

Good question. The compiler says `Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.`
So I think we should follow that directive. Here's an example of a diff that fixes the warning in `Abs_BaseCrossDomainMessenger.sol`. You also need to modify the natspec comments to remove the param. 

![image](https://user-images.githubusercontent.com/23033765/109988770-dba78800-7cd5-11eb-8915-0305efbccc2a.png)




> * should we also attempt to remove warnings originating from `UniswapV2ERC20`

Yes, I think so.

2021-03-05 02:53 UTC, maurelian commented
> > * what should we rename [push2](https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/libraries/utils/Lib_RingBuffer.sol#L121) to?
> 
> Let's try `pushTwo`, and we'll see what the other maintainers think when the full PR is ready for review.

I'm sorry, I've changed my mind about that. Let's not change `push2` for now.

2021-03-08 15:40 UTC, vaibhavchellani commented
I have some changes to push, do you prefer me to send those as a 2nd PR?

2021-03-08 18:37 UTC, maurelian approved these changes

2021-03-08 18:50 UTC, merged